export const patternImages = [
  { value: "none", label: "なし" },
  { value: "gakucho-01", label: "学長" },
  { value: "worker-01", label: "リーマンくん" },
  { value: "house-01", label: "主婦ちゃん" },
  { value: "free-01", label: "フリーランス君" },
  { value: "ol-01", label: "OLちゃん" },
  { value: "pattern-00", label: "ハート" },
  { value: "pattern-01", label: "お花" },
  { value: "pattern-02", label: "音符" },
  { value: "pattern-03", label: "お魚" },
  { value: "pattern-04", label: "お星様" },
  { value: "pattern-05", label: "お金" },
  { value: "pattern-06", label: "コーヒー豆" },
  { value: "pattern-07", label: "カブトムシ" },
  { value: "pattern-08", label: "野球ボール" },
  { value: "pattern-09", label: "おめめ" },
  { value: "pattern-10", label: "初心者マーク" },
  { value: "pattern-11", label: "メガネ" },
  { value: "pattern-12", label: "ひげ" },
  { value: "pattern-13", label: "温泉" },
  { value: "pattern-14", label: "ラーメン" },
  { value: "pattern-15", label: "梅の花" },
  { value: "pattern-16", label: "スイカ" },
  { value: "pattern-17", label: "パイナップル" },
  { value: "pattern-18", label: "鉱石" },
];
